WIP: feature: Sponsors admin & API functionality
SwiftLeeds/swiftleeds-web pull request #49
Opened 2022-07-20 23:25 UTC by adamoxley

# Changes

- Adds in admin sponsor (create)
- Adds in admin API sponsor functionality (create, edit)
- Adds in new ImageService class for uploading to S3
- Adds in new `S3_BUCKET_NAME` environment (note: this will need added to CI for prod if we choose to use it, IMO, it's good for local dev to have it in)
- Updates website to use new sponsor API

# TODO

- Admin edit sponsor functionality
- Admin delete sponsor functionality
- Mobile API sponsor `GET` endpoint  

# Notes

- SVG seem to not work for some reason, I think due to how the S3 uploads are done, the SVG files appear correct (and download correct) directly from the S3 bucket, but don't show in Safari or Chrome. I suggest we use PNG's going forward, as these would render on iOS just fine also.
- The way sponsors are done right now is passing in each individual sponsor level into `HomeContext`, I've done this due to Leaf templates not supporting dictionaries and not sure what other way to approach it. Suggestions welcome.

# Screenshots

## Create Sponsor

<img width="1349" alt="Screenshot 2022-07-21 at 00 13 19" src="https://user-images.githubusercontent.com/5316805/180098849-93f2f7fb-2935-4f9b-bd3c-7bfc8972fb98.png">

## Create Sponsor (sponsor level section)

<img width="477" alt="Screenshot 2022-07-21 at 00 13 36" src="https://user-images.githubusercontent.com/5316805/180098897-2c44a147-5dfb-4eea-a711-6e8417d9bd72.png">

## Admin Sponsor List

<img width="1336" alt="Screenshot 2022-07-21 at 00 12 55" src="https://user-images.githubusercontent.com/5316805/180098928-d0f8ea4c-6cc0-4a17-b19b-75f108b407d3.png">

## Website Sponsor List

<img width="1399" alt="Screenshot 2022-07-21 at 00 12 46" src="https://user-images.githubusercontent.com/5316805/180098954-c235de91-26f7-433f-8625-2656e10788bd.png">

2022-07-20 23:26 UTC, adamoxley commented on Resources/Views/Home/_speakers.leaf
> +                    <img class="speaker-grid-element-image" src="https://swift-leeds.s3.eu-west-2.amazonaws.com/#(speaker.profileImage)"/>
Whoops. This is my local bucket. Will swap it back before it gets merged in.

2022-07-21 18:13 UTC, SwiftyAlex requested changes
Just the one thought, looks great!

2022-07-21 21:33 UTC, adamoxley commented on Sources/App/Features/Sponsors/Models/Sponsor.swift
> +    var image: String
So I couldn't get web to display uploaded SVG's. I think its the way we use `S3.PutObjectRequest` but I'm honestly not sure. They uploaded fine into the S3 bucket and I could download from the S3 bucket and view them locally, but they never displayed on the web using the same `img` code as was in using local SVG's. 

I'd say if we use PNG's for now it's probably _fine_ for both platforms?

2022-07-21 21:40 UTC, adamoxley commented
@adamrushy @SwiftyAlex @pdamonkey 

Ready for review.

I haven't included the mobile API into this PR as I think that needs some discussion amongst the team as to how we're going to structure the mobile APIs away from the admin APIs which route under `api/v1` (I think if I'm remembered correctly). But this at least lays all the ground work for the sponsor API.

Updated the main PR description with the latest screenshots of the website & admin panel. Included in the edit sponsor web page is a preview of the existing sponsors image, as it isn't possible to pre-populate a file input field, if no file is uploaded on edit sponsor, the old image is kept.

Before merging this in we will need to ensure two things;
- A new env key gets added to hosting for S3_BUCKET_NAME
- We have all the sponsor images / other info ready to re-upload. Images should be in PNG format (a few sponsors have supplied them as SVG).

2022-07-21 21:41 UTC, adamoxley commented on Resources/Views/Home/_speakers.leaf
> +                    <img class="speaker-grid-element-image" src="https://swift-leeds.s3.eu-west-2.amazonaws.com/#(speaker.profileImage)"/>
I've changed back but GitHub isn't seeing this as an outdated comment for some reason. Will resolve conversation instead.

2022-07-22 08:50 UTC, SwiftyAlex commented on Sources/App/Features/Sponsors/Models/Sponsor.swift
> +    var image: String
very weird! ok, lets rock with these for now, we'll just have to make sure those pngs are _crispy_ 👍🏻

2022-07-27 21:30 UTC, merged